# coding: utf-8

"""
    Grid Tariff API

    Provides grid tariffs from Swedish DSOs.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.component_prices import ComponentPrices

class TestComponentPrices(unittest.TestCase):
    """ComponentPrices unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ComponentPrices:
        """Test ComponentPrices
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ComponentPrices`
        """
        model = ComponentPrices()
        if include_optional:
            return ComponentPrices(
                component_id = '216783ff-5dda-4c38-b491-d6f0fcee9a9b',
                prices = [
                    openapi_client.models.price_period.PricePeriod(
                        valid_period = openapi_client.models.date_time_interval.DateTimeInterval(
                            from_including = '2024-09-17T00:00:00+01:00', 
                            to_excluding = '204-09-17T01:00:00+01:00', ), 
                        price = openapi_client.models.price.Price(
                            price_ex_vat = 1.337, 
                            price_inc_vat = 1.337, 
                            currency = 'SEK', ), )
                    ]
            )
        else:
            return ComponentPrices(
        )
        """

    def testComponentPrices(self):
        """Test ComponentPrices"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
