# coding: utf-8

"""
    Grid Tariff API

    Provides grid tariffs from Swedish DSOs.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.tariffs_search_request import TariffsSearchRequest

class TestTariffsSearchRequest(unittest.TestCase):
    """TariffsSearchRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TariffsSearchRequest:
        """Test TariffsSearchRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TariffsSearchRequest`
        """
        model = TariffsSearchRequest()
        if include_optional:
            return TariffsSearchRequest(
                metering_point_ids = [
                    '735999000000000001'
                    ]
            )
        else:
            return TariffsSearchRequest(
        )
        """

    def testTariffsSearchRequest(self):
        """Test TariffsSearchRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
