# coding: utf-8

"""
    Grid Tariff API

    Provides grid tariffs from Swedish DSOs.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.price_api import PriceApi


class TestPriceApi(unittest.TestCase):
    """PriceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PriceApi()

    def tearDown(self) -> None:
        pass

    def test_get_prices(self) -> None:
        """Test case for get_prices

        Returns prices for a price component for a given timeperiod.
        """
        pass


if __name__ == '__main__':
    unittest.main()
