# coding: utf-8

"""
    Grid Tariff API

    Provides grid tariffs from Swedish DSOs.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.tariff_api import TariffApi


class TestTariffApi(unittest.TestCase):
    """TariffApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TariffApi()

    def tearDown(self) -> None:
        pass

    def test_get_tariff_by_id(self) -> None:
        """Test case for get_tariff_by_id

        Returns the tariff for the provided id.
        """
        pass

    def test_get_tariffs(self) -> None:
        """Test case for get_tariffs

        Returns a collection of publicly available tariffs for the DSO without any customer data.
        """
        pass

    def test_search_tariffs(self) -> None:
        """Test case for search_tariffs

        Returns a collection of tariffs based on the search criteria and a mapping between the tariffs and search parameters.
        """
        pass


if __name__ == '__main__':
    unittest.main()
