# coding: utf-8

"""
    Grid Tariff API

    Provides grid tariffs from Swedish DSOs.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.peak_identification_settings import PeakIdentificationSettings

class TestPeakIdentificationSettings(unittest.TestCase):
    """PeakIdentificationSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PeakIdentificationSettings:
        """Test PeakIdentificationSettings
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PeakIdentificationSettings`
        """
        model = PeakIdentificationSettings()
        if include_optional:
            return PeakIdentificationSettings(
                peak_function = 'peak(main)',
                peak_identification_period = '',
                peak_duration = '',
                number_of_peaks_for_average_calculation = 3
            )
        else:
            return PeakIdentificationSettings(
        )
        """

    def testPeakIdentificationSettings(self):
        """Test PeakIdentificationSettings"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
