# coding: utf-8

"""
    Grid Tariff API

    Provides grid tariffs from Swedish DSOs.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from openapi_client.models.date_interval import DateInterval
from openapi_client.models.peak_identification_settings import PeakIdentificationSettings
from openapi_client.models.price import Price
from openapi_client.models.recurring_period import RecurringPeriod
from typing import Optional, Set
from typing_extensions import Self

class PowerPriceComponent(BaseModel):
    """
    A time period in which pricing and power peak identification details are defined. Price components can be overlapping in time to define the full price for one time period.
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, description="Globally unique identifier")
    name: Optional[StrictStr] = Field(default=None, description="A short human readable name.")
    description: Optional[StrictStr] = Field(default=None, description="A longer explanatory text.")
    type: Optional[Annotated[str, Field(strict=True)]] = 'peak'
    reference: Optional[StrictStr] = Field(default='main', description="Reference to be used to identify this recurring price period in the cost function.")
    price: Optional[Price] = None
    valid_period: Optional[DateInterval] = Field(default=None, alias="validPeriod")
    peak_identification_settings: Optional[PeakIdentificationSettings] = Field(default=None, alias="peakIdentificationSettings")
    recurring_periods: Optional[List[RecurringPeriod]] = Field(default=None, alias="recurringPeriods")
    __properties: ClassVar[List[str]] = ["id", "name", "description", "type", "reference", "price", "validPeriod", "peakIdentificationSettings", "recurringPeriods"]

    @field_validator('type')
    def type_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"peak|dynamic", value):
            raise ValueError(r"must validate the regular expression /peak|dynamic/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PowerPriceComponent from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of price
        if self.price:
            _dict['price'] = self.price.to_dict()
        # override the default output from pydantic by calling `to_dict()` of valid_period
        if self.valid_period:
            _dict['validPeriod'] = self.valid_period.to_dict()
        # override the default output from pydantic by calling `to_dict()` of peak_identification_settings
        if self.peak_identification_settings:
            _dict['peakIdentificationSettings'] = self.peak_identification_settings.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in recurring_periods (list)
        _items = []
        if self.recurring_periods:
            for _item_recurring_periods in self.recurring_periods:
                if _item_recurring_periods:
                    _items.append(_item_recurring_periods.to_dict())
            _dict['recurringPeriods'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PowerPriceComponent from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "type": obj.get("type") if obj.get("type") is not None else 'peak',
            "reference": obj.get("reference") if obj.get("reference") is not None else 'main',
            "price": Price.from_dict(obj["price"]) if obj.get("price") is not None else None,
            "validPeriod": DateInterval.from_dict(obj["validPeriod"]) if obj.get("validPeriod") is not None else None,
            "peakIdentificationSettings": PeakIdentificationSettings.from_dict(obj["peakIdentificationSettings"]) if obj.get("peakIdentificationSettings") is not None else None,
            "recurringPeriods": [RecurringPeriod.from_dict(_item) for _item in obj["recurringPeriods"]] if obj.get("recurringPeriods") is not None else None
        })
        return _obj


