# coding: utf-8

"""
    Grid Tariff API

    Provides grid tariffs from Swedish DSOs.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.active_period import ActivePeriod

class TestActivePeriod(unittest.TestCase):
    """ActivePeriod unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ActivePeriod:
        """Test ActivePeriod
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ActivePeriod`
        """
        model = ActivePeriod()
        if include_optional:
            return ActivePeriod(
                from_including = '00:00:00',
                to_excluding = '01:00:00',
                calendar_pattern_references = openapi_client.models.calendar_pattern_references.CalendarPatternReferences(
                    include = [
                        ''
                        ], 
                    exclude = [
                        ''
                        ], )
            )
        else:
            return ActivePeriod(
        )
        """

    def testActivePeriod(self):
        """Test ActivePeriod"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
