# coding: utf-8

"""
    Grid Tariff API

    Provides grid tariffs from Swedish DSOs.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.tariff_mapping import TariffMapping

class TestTariffMapping(unittest.TestCase):
    """TariffMapping unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TariffMapping:
        """Test TariffMapping
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TariffMapping`
        """
        model = TariffMapping()
        if include_optional:
            return TariffMapping(
                tariff_id = '216783ff-5dda-4c38-b491-d6f0fcee9a9b',
                metering_point_ids = [
                    '735999000000000001'
                    ]
            )
        else:
            return TariffMapping(
        )
        """

    def testTariffMapping(self):
        """Test TariffMapping"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
