# coding: utf-8

"""
    Grid Tariff API

    Provides grid tariffs from Swedish DSOs.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.energy_price_component import EnergyPriceComponent
from typing import Optional, Set
from typing_extensions import Self

class EnergyPrice(BaseModel):
    """
    Prices and information for the energy price component of the tariff.
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, description="Globally unique identifier")
    name: Optional[StrictStr] = Field(default=None, description="A short human readable name.")
    description: Optional[StrictStr] = Field(default=None, description="A longer explanatory text.")
    cost_function: Optional[StrictStr] = Field(default=None, description="A pseudo code function that describes how to calculate the cost for a set of price components. Usage examples at https://someexamples.", alias="costFunction")
    unit: Optional[StrictStr] = Field(default=None, description="The unit of a measurement or price calculation.")
    components: Optional[List[EnergyPriceComponent]] = None
    __properties: ClassVar[List[str]] = ["id", "name", "description", "costFunction", "unit", "components"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EnergyPrice from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in components (list)
        _items = []
        if self.components:
            for _item_components in self.components:
                if _item_components:
                    _items.append(_item_components.to_dict())
            _dict['components'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EnergyPrice from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "costFunction": obj.get("costFunction"),
            "unit": obj.get("unit"),
            "components": [EnergyPriceComponent.from_dict(_item) for _item in obj["components"]] if obj.get("components") is not None else None
        })
        return _obj


