# coding: utf-8

"""
    Grid Tariff API

    Provides grid tariffs from Swedish DSOs.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class PeakIdentificationSettings(BaseModel):
    """
    Settings that defines how to identify a power peak during a billing period.
    """ # noqa: E501
    peak_function: Optional[StrictStr] = Field(default='peak(main)', description="A pseudo code function that describes how to identify a power peak for one power price component. Usage examples at https://someexamples.", alias="peakFunction")
    peak_identification_period: Optional[StrictStr] = Field(default=None, description="A time duration in the format [ISO 8601 duration format](https://en.wikipedia.org/wiki/ISO_8601#Durations). Examples: - \"P1D\" for one day - \"P1M\" for one month - \"P2W\" for two weeks - \"P3Y6M4DT12H30M5S\" for a complex duration.", alias="peakIdentificationPeriod")
    peak_duration: Optional[StrictStr] = Field(default=None, description="A time duration in the format [ISO 8601 duration format](https://en.wikipedia.org/wiki/ISO_8601#Durations). Examples: - \"P1D\" for one day - \"P1M\" for one month - \"P2W\" for two weeks - \"P3Y6M4DT12H30M5S\" for a complex duration.", alias="peakDuration")
    number_of_peaks_for_average_calculation: Optional[StrictInt] = Field(default=None, description="The number of peaks within a peak pricing period for calculating average peak for that period.", alias="numberOfPeaksForAverageCalculation")
    __properties: ClassVar[List[str]] = ["peakFunction", "peakIdentificationPeriod", "peakDuration", "numberOfPeaksForAverageCalculation"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PeakIdentificationSettings from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PeakIdentificationSettings from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "peakFunction": obj.get("peakFunction") if obj.get("peakFunction") is not None else 'peak(main)',
            "peakIdentificationPeriod": obj.get("peakIdentificationPeriod"),
            "peakDuration": obj.get("peakDuration"),
            "numberOfPeaksForAverageCalculation": obj.get("numberOfPeaksForAverageCalculation")
        })
        return _obj


