# coding: utf-8

"""
    Grid Tariff API

    Provides grid tariffs from Swedish DSOs.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from openapi_client.models.date_interval import DateInterval
from openapi_client.models.energy_price import EnergyPrice
from openapi_client.models.fixed_price import FixedPrice
from openapi_client.models.power_price import PowerPrice
from typing import Optional, Set
from typing_extensions import Self

class Tariff(BaseModel):
    """
    Information about the tariff that are static and does not change during at least a month.
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, description="Globally unique identifier")
    name: Optional[StrictStr] = Field(default=None, description="Descriptive short name of the grid tariff.")
    description: Optional[StrictStr] = Field(default=None, description="Detailed description of the grid tariff.")
    product: Optional[StrictStr] = Field(default=None, description="Name of the grid company product, for grid company internal use.")
    company_name: Optional[StrictStr] = Field(default=None, description="Name of the grid company.", alias="companyName")
    company_org_no: Optional[StrictStr] = Field(default=None, description="Organization number of the grid company.", alias="companyOrgNo")
    direction: Optional[Annotated[str, Field(strict=True)]] = Field(default='consumption', description="Indicates if this is a tariff for consumption or production. Valid values are \"consumption\" and \"production\".")
    time_zone: Optional[StrictStr] = Field(default=None, description="Time zone for all time values in this tariff. From the IANA Time Zone Database (e.g., 'Europe/Stockholm').", alias="timeZone")
    last_updated: Optional[datetime] = Field(default=None, description="The time of when the prices were last updated on the server side. No need to get prices if you already fetched the latest ones? Ex. 2021-11-05T00:00:00+01:00", alias="lastUpdated")
    valid_period: Optional[DateInterval] = Field(default=None, alias="validPeriod")
    billing_period: Optional[StrictStr] = Field(default=None, description="A time duration in the format [ISO 8601 duration format](https://en.wikipedia.org/wiki/ISO_8601#Durations). Examples: - \"P1D\" for one day - \"P1M\" for one month - \"P2W\" for two weeks - \"P3Y6M4DT12H30M5S\" for a complex duration.", alias="billingPeriod")
    fixed_price: Optional[FixedPrice] = Field(default=None, alias="fixedPrice")
    energy_price: Optional[EnergyPrice] = Field(default=None, alias="energyPrice")
    power_price: Optional[PowerPrice] = Field(default=None, alias="powerPrice")
    __properties: ClassVar[List[str]] = ["id", "name", "description", "product", "companyName", "companyOrgNo", "direction", "timeZone", "lastUpdated", "validPeriod", "billingPeriod", "fixedPrice", "energyPrice", "powerPrice"]

    @field_validator('direction')
    def direction_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"consumption|production", value):
            raise ValueError(r"must validate the regular expression /consumption|production/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Tariff from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of valid_period
        if self.valid_period:
            _dict['validPeriod'] = self.valid_period.to_dict()
        # override the default output from pydantic by calling `to_dict()` of fixed_price
        if self.fixed_price:
            _dict['fixedPrice'] = self.fixed_price.to_dict()
        # override the default output from pydantic by calling `to_dict()` of energy_price
        if self.energy_price:
            _dict['energyPrice'] = self.energy_price.to_dict()
        # override the default output from pydantic by calling `to_dict()` of power_price
        if self.power_price:
            _dict['powerPrice'] = self.power_price.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Tariff from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "product": obj.get("product"),
            "companyName": obj.get("companyName"),
            "companyOrgNo": obj.get("companyOrgNo"),
            "direction": obj.get("direction") if obj.get("direction") is not None else 'consumption',
            "timeZone": obj.get("timeZone"),
            "lastUpdated": obj.get("lastUpdated"),
            "validPeriod": DateInterval.from_dict(obj["validPeriod"]) if obj.get("validPeriod") is not None else None,
            "billingPeriod": obj.get("billingPeriod"),
            "fixedPrice": FixedPrice.from_dict(obj["fixedPrice"]) if obj.get("fixedPrice") is not None else None,
            "energyPrice": EnergyPrice.from_dict(obj["energyPrice"]) if obj.get("energyPrice") is not None else None,
            "powerPrice": PowerPrice.from_dict(obj["powerPrice"]) if obj.get("powerPrice") is not None else None
        })
        return _obj


